/* ============ 共享作品数据（主页 + 通用详情页） ============ */
/* cat: land = 风景图 / portrait = 人物图 / anime = 动画图 */
const WORKS = [
  { name:"《北境极光》", img:"images/landscape/land-01.jpg", price:"¥1880", type:"风景图", cat:"land",
    desc:"在极北寒夜记录绿色极光跃动于雪山之巅", time:"2026 · 冬",
    tags:["极光","长曝光","极北"],
    bg:"一场盛大的绿色极光整夜舞动于雪原上空。我选择长曝光与低色温记录这段属于极北的蓝紫色柔情，山与天在此刻融为一体。" },
  { name:"《天空之城》", img:"images/anime/anime-04.jpg", price:"¥2380", type:"动画图", cat:"anime",
    desc:"以宫崎骏式浪漫描绘漂浮于云端的城市", time:"2024 · 夏",
    tags:["夜色","幻想","宫崎骏"],
    bg:"灵感来自漂浮在云端的奇幻城市。青蓝的天际与霓虹交织出浪漫而神秘的夜色，是我对幻想世界的一封情书。" },
  { name:"《故乡的人》", img:"images/portrait/port-01.jpg", price:"¥980", type:"人物图", cat:"portrait",
    desc:"用镜头留住故乡土地上每一张质朴的脸", time:"2026 · 春",
    tags:["人文","纪实","温暖"],
    bg:"回到故乡，我用镜头留住土地上最质朴的脸。风霜里藏着的温柔与坚定，正是我最想记录的人间温度。" },
  { name:"《移动的城堡》", img:"images/anime/anime-02.jpg", price:"¥2680", type:"动画图", cat:"anime",
    desc:"致敬哈尔的移动城堡，蒸汽与魔法的黄昏", time:"2025 · 秋",
    tags:["致敬宫崎骏","蒸汽朋克"],
    bg:"致敬《哈尔的移动城堡》，那座踏着蒸汽行走的房子，是无数人关于自由与回家的浪漫寓言。柔和蓝金的光，是我心中最温柔的黄昏。" },
  { name:"《晨光山海》", img:"images/home/landscape-3.jpg", price:"¥1580", type:"风景图", cat:"land",
    desc:"第一缕阳光点亮山脉轮廓的壮阔时刻", time:"2025 · 冬",
    tags:["日出","山峦"],
    bg:"清晨第一缕阳光点亮了山脉的轮廓，冷峻的北境在此刻被镀上暖色，也唤醒了沉睡的山海。" },
  { name:"《夏日微光》", img:"images/portrait/port-05.jpg", price:"¥1280", type:"人物图", cat:"portrait",
    desc:"捕捉夏日阳光里温柔而鲜活的人", time:"2024 · 夏",
    tags:["肖像","氛围"],
    bg:"镜头下她眼底藏着整个夏天。我对准自然光里最松弛的瞬间，把当下的鲜活与心事一并封存。" },
  { name:"《湖畔冬雪》", img:"images/landscape/land-06.jpg", price:"¥1280", type:"风景图", cat:"land",
    desc:"雪覆湖畔，寂静与纯粹并存的一刻", time:"2023 · 冬",
    tags:["雪景","静美"],
    bg:"雪覆湖畔，天地陷入深深的寂静。我想把这份纯粹与留白留给观者——有些美不需要解释，只需安静地看。" },
  { name:"《荒原归途》", img:"images/anime/anime-01.jpg", price:"¥1680", type:"动画图", cat:"anime",
    desc:"绝美原野上一个人的漫长归途", time:"2026 · 春",
    tags:["原野","逐梦"],
    bg:"少年背起行囊走向原野尽头，风与云替他引路。前方是未知，也是归途与希望。" },
  { name:"《雪岭晨光》", img:"images/landscape/land-02.jpg", price:"¥1580", type:"风景图", cat:"land",
    desc:"清晨第一缕光为雪岭镀上暖色", time:"2025 · 冬",
    tags:["日出","雪岭"],
    bg:"清晨的光越过雪岭，为冷峻的山脊镀上一层暖色。冷暖在此交汇，安静又有力量。" },
  { name:"《春风与奔赴》", img:"images/portrait/port-03.jpg", price:"¥1180", type:"人物图", cat:"portrait",
    desc:"出发前凝望远方，踏上自己的旅途", time:"2025 · 春",
    tags:["旅途","希望"],
    bg:"他戴着旧帽踏上旅途，我拍下他出发前专注望向远方的样子。人生也像这样，一步步奔赴属于自己的远方。" },
  { name:"《天空的约定》", img:"images/anime/anime-05.png", price:"¥2480", type:"动画图", cat:"anime",
    desc:"云与风的流动，动画的呼吸感", time:"2024 · 秋",
    tags:["云海","梦幻"],
    bg:"云与风在画面上流动，仿佛能听见风穿过云层的声音。这是属于动画的呼吸感，也是我与天空的约定。" },
  { name:"《弧光之境》", img:"images/landscape/land-04.jpg", price:"¥2180", type:"风景图", cat:"land",
    desc:"极光在湖面投下流动的倒影", time:"2024 · 春",
    tags:["湖光","极光"],
    bg:"极光在湖面上投下流动的倒影，天地之间仿佛被同一束光连接。那份对称的宁静，至今难忘。" },
  { name:"《灯下的我们》", img:"images/portrait/port-06.jpg", price:"¥980", type:"人物图", cat:"portrait",
    desc:"黑暗中一盏灯照亮的温暖与坚持", time:"2023 · 冬",
    tags:["夜","点光"],
    bg:"她提着一盏灯站在夜色里，光从指尖流淌。我想表达黑暗中一盏灯照亮的温度，与那份不肯熄灭的坚持。" },
  { name:"《清晨的第一束光》", img:"images/anime/anime-06.jpg", price:"¥1680", type:"动画图", cat:"anime",
    desc:"晨光撕开夜色，为天空镀上金边", time:"2023 · 春",
    tags:["晨光","治愈"],
    bg:"晨光撕开夜色，为整片天空镀上金边。世界慢慢醒来，温柔如初，美好如期而至。" },
  { name:"《暖阳下的笑》", img:"images/portrait/port-04.jpg", price:"¥1380", type:"人物图", cat:"portrait",
    desc:"冬日暖阳里明亮而松弛的笑容", time:"2024 · 冬",
    tags:["暖调","笑容"],
    bg:"冬日暖阳把她整个包裹起来，笑容明亮而松弛。我想这就是被生活温柔以待、认真活着的样子。" },
  { name:"《午后的风》", img:"images/portrait/port-02.jpg", price:"¥1080", type:"人物图", cat:"portrait",
    desc:"少年在树荫下打盹的松弛午后，风轻扬起衣角", time:"2025 · 夏",
    tags:["少年","自然光"],
    bg:"少年在午后的树荫下打盹，风把衣角轻轻扬起。这一刻的松弛与安静，几乎能闻见草木的气息。" },
  { name:"《黄昏后的归处》", img:"images/anime/anime-03.jpg", price:"¥1580", type:"动画图", cat:"anime",
    desc:"暮色四合，农舍亮起暖黄灯火，温柔而安定", time:"2025 · 冬",
    tags:["黄昏","暖光"],
    bg:"暮色四合，农舍亮起暖黄的灯。温柔的留白与光线，像极了宫崎骏笔下让人安心的黄昏。" }
];

/* 分类导航链接 */
const CATLINK = {
  land:    "pages/landscape.html",
  portrait:"pages/portrait.html",
  anime:   "pages/anime.html"
};

/* 分类主题名（用于详情页 body class） */
const CATTHEME = { land:"theme-landscape", portrait:"theme-portrait", anime:"theme-anime" };